### PR TITLE
class uses 'pools' hiera key, not 'pool'

### PR DESCRIPTION
**Pull request by vchepkov**
either module has to be changed or the documentation.
I would change module instead, since it's not intuitive, but this would create an incompatibility with current configurations

### CODE REVIEW

**Comment by mmoll** [comment]
the corresponding class-syntax in line 108 also needs changing then.

**Comment by vchepkov** [comment]
Not sure I follow.
I am pointing to this line of code:
https://github.com/mayflower/puppet-php/blob/master/manifests/fpm.pp#L77

it uses `hiera_hash('php::fpm::pools')`

**Comment by mmoll** [comment]
@vchepkov oh, I see... that's correct, merged. That was a fallout of a recent readme change and the original code change was one of the steps to make this module more hiera-centric.
Спасибо @vchepkov!

**Comment by vchepkov** [comment]
Bitte schön

**Pull request merged**
