### PR TITLE
fix trusty default php5-fpm / php5enmod name, disable xml dependency

### PR DESCRIPTION
**Pull request by marcofl**
this fixes fpm service name on Ubuntu Trusty 14.04 as there using default version.

### CODE REVIEW

**Comment by mmoll** [comment]
@tdm4 could you have a look?

**Comment by tdm4** [comment]
Only issue here, I think is, what if you install 5.5 from Ondřej Surý's repo instead of Ubuntu's base repos? Though I think, since we set Ubuntu systems to use that repo, this shouldn't be a problem.

**Comment by mmoll** [comment]
OK, I'm getting the problem now... I'll reproduce as soon as I have time. If the PPA is enabled by default there should indeed be no problem. If the PPA is disabled, the other params need to get set to match, too.

**Comment by mmoll** [comment]
Tested and as we do enable the PPA by default everything is fine.

If the PPA is explicitly disabled, the parameters in `::php::globals`  need to get explicitly overridden, too...

@marcofl could you open a PR to the README for that? Maybe around "Ubuntu systems and Ondřej's PPA"...

**Pull request closed without merging**
