### PR TITLE
Remove php::repo::ubuntu::ppa

### PR DESCRIPTION
**Pull request by tdm4**
Removes php::repo::ubuntu::ppa (Issue #214 )
Also removes reference to it in README.md

### CODE REVIEW

**Comment by tdm4** [comment]
@mmoll Is it possible the CI checks are using cached information? The `bundle exec rake spec` run on my system checks out fine with no errors.

**Comment by tdm4** [comment]
@mmoll Can you tell it to re-run the spec tests? They come out as fine (no errors) on my system. I think the Travis-CI system got confused with 2 commits in a short amount of time.

**Comment by mmoll** [comment]
I'll re-run them soon, as voxpupuli/puppet-lint-absolute_classname-check#6 will be resolved in the next hour or so.

**Comment by tdm4** [comment]
@mmoll  I guess they eventually ran on their own!

**Comment by mmoll** [comment]
Nope, I did restart them :fire_engine:
This change is fine, merging...
Thanks again @tdm4!

**Comment by tdm4** [comment]
Great stuff! Thanks @mmoll !

**Pull request merged**
