### PR TITLE
make to_hash_settings backwards compatible and update documentation

### PR DESCRIPTION
**Pull request by elseym**

### CODE REVIEW

**Comment by fpletz** [comment]
LGTM :+1:

**Comment by elseym** [comment]
waaitasecond. imma add a test.

**Comment by fpletz** [comment]
This should fix the test: https://github.com/elseym/puppet-php/compare/fix-to_hash_settings...mayflower:fix-to_hash_settings

**Comment by elseym** [comment]
woohoo!

**Comment by globin** [comment]
Could you please squash the commits and then I'll merge :+1:

**Pull request merged**
