### PR TITLE
Correcting dependency for globals class

### PR DESCRIPTION
**Pull request by craigwatson**

### CODE REVIEW

**Comment by mmoll** [comment]
Could you please re-check this, as #192 was merged?

**Comment by chrisboulton** [comment]
I think we still want this (after a rebase) - it's what I mentioned in #191 but hadn't managed to get around to submitting a PR for. #192 just removed the global sales functionality from Debian systems - RedHat, etc will still experience the ordering issue.

**Comment by craigwatson** [comment]
@mmoll just rebased this to include #192 

@chrisboulton Thanks - I experienced the same problem in in Ubuntu, but I had the Apache/CLI files symlinked to `/etc/php5/php.ini` outside of the module so the global was actually in use. 

Happy for this to be merged if it will be useful for non-Debian OSes :)

**Comment by mmoll** [comment]
@chrisboulton so, this PR fixes #191?

**Comment by chrisboulton** [comment]
Should do!

Sent from my iPhone

On Jun 11, 2016, at 4:56 PM, Michael Moll <notifications@github.com> wrote:

@chrisboulton <https://github.com/chrisboulton> so, this PR fixes #191
<https://github.com/mayflower/puppet-php/issues/191>?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mayflower/puppet-php/pull/194#issuecomment-225396708>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAGAqJZxVtTW47NvvtSzyIz8daNnfqj6ks5qKy8qgaJpZM4IzoFe>
.

**Comment by mmoll** [comment]
perfect, merged. thanks!

**Pull request merged**
