### PR TITLE
get closer to Puppet4 readyness

### PR DESCRIPTION
**Pull request by mmoll**
Comments please :newspaper:, there are two tests failing, maybe @globin has an idea about the inifile paramter, and I still have to think over the spaceship operator, as long as nobody else has a quick solution for that.

### CODE REVIEW

**Comment by globin** [comment]
Is it possible to turn of the empty string lint for that line? We actually want that there because of php.ini weirdness having no section/an empty section in a few places.

And we always want to make sure we always restart fpm after installing/changing extensions even if we don't define them. Hence the empty spaceship is fully intended.

Are those not allowed in Puppet4 or is that just fancy "hack-freeness"?

**Comment by mmoll** [comment]
I don't think it's possible to turn off the check for just one line. See http://www.camptocamp.com/actualite/getting-code-ready-puppet-4/ for details on the checks. I would be OK to turn off the spaceship check if there's no good solution, especially as I used it in the past, too. ;)

**Comment by globin** [comment]
http://puppet-lint.com/controlcomments/

**Comment by mmoll** [comment]
Ah, nice, didn't know that. :bow:
However, would ```undef``` instead of ```''``` also do the trick for inifile?

**Comment by globin** [comment]
If it's allowed here: https://github.com/puppetlabs/puppetlabs-inifile/blob/master/lib/puppet/util/ini_file.rb#L12

I don't know, someone ( :panda_face: ) will have to try,

**Comment by mmoll** [comment]
doesn't work with ```undef``` :crying_cat_face:

**Comment by mmoll** [comment]
All :green_heart: now, for your kind consideration.
BTW, we really need more spec tests, I don't think this is really future parser ready...

**Comment by globin** [comment]
Go for it :wink:

**Pull request merged**
